<?php
/**
 * Magestore
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Magestore.com license that is
 * available through the world-wide-web at this URL:
 * http://www.magestore.com/license-agreement.html
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this extension to newer
 * version in the future.
 *
 * @category    Magestore
 * @package     Magestore_Inventory
 * @copyright   Copyright (c) 2012 Magestore (http://www.magestore.com/)
 * @license     http://www.magestore.com/license-agreement.html
 */

class Magestore_Inventorystoresfinder_Block_Adminhtml_Warehouse_Edit_Tab_Location extends Mage_Adminhtml_Block_Widget_Form {

    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->setTemplate('inventorystoresfinder/widget/form.phtml');
    }

    protected function _prepareForm() {

        $form = new Varien_Data_Form();
        $this->setForm($form);
        if (Mage::getSingleton('adminhtml/session')->getWarehouseData()) {
            $warehouse = Mage::getSingleton('adminhtml/session')->getWarehouseData();
            Mage::getSingleton('adminhtml/session')->setWarehouseData(null);
        } elseif (Mage::registry('warehouse_data')) {
            $warehouse = Mage::registry('warehouse_data')->getData();
        }
        //Mage::log($warehouse);
        $data = array();
        if($warehouse){
            $location = Mage::getModel('inventorystoresfinder/warehouse_location')->load($warehouse['warehouse_id']);
            $data = $location->getData();
            if(!$data['store_address'])$data['store_address']= Mage::helper('inventorystoresfinder')->getWarehouseAddress($warehouse['warehouse_id']);
        }

        $fieldset = $form->addFieldset('warehouse_location_form', array(
            'legend' => Mage::helper('inventoryplus')->__('Warehouse Information')
        ));
        $yesnoSource = Mage::getModel('adminhtml/system_config_source_yesno')->toOptionArray();

        $fieldset->addField('store_address', 'text', array(
            'label' => Mage::helper('inventoryplus')->__('Store Address'),
            'class' => 'required-entry',
            'required' => true,
            'name' => 'store_address',
        ));

        $fieldset->addField('lat', 'text', array(
            'label' => Mage::helper('inventoryplus')->__('Latitude'),
            'class' => 'required-entry',
            'readonly' => true,
            'name' => 'lat',
        ));
        $fieldset->addField('lng', 'text', array(
            'label' => Mage::helper('inventoryplus')->__('Longitude'),
            'class' => 'required-entry',
            'readonly' => true,
            'name' => 'lng',
        ));

        $fieldset->addField('is_store', 'select', array(
            'label' => Mage::helper('inventoryplus')->__('Warehouse is Store'),
            'class' => 'required-entry',
            'values' => $yesnoSource,
            'required' => true,
            'name' => 'is_store',
        ));
        
        $form->setValues($data);
        return parent::_prepareForm();
    }
}